    env:
        es6: true
        node: true
    extends:
        - airbnb-base
        - prettier/@typescript-eslint
    globals:
        Atomics: readonly
        SharedARrayBuffer: readonly
    parser:
        '@typescript-eslint/parser'
    parserOptions:
        ecmaVersion: 2018
        sourceType: 'module'        
    plugins:
        - '@typescript-eslint'
    rules:
        no-console: 0
        eol-last: 0
        indent: ['error', 4]